version: '3.8'
services:
  service:
    image: de.axitera/mosesonline/mymeetup:latest
    environment:
      - KAFKA_HOST=172.21.171.70
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    ports:
      - 28080:8080
      - 28000:8000
    depends_on:
      - database
      - kafka
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetup
  kafka:
    image: lensesio/fast-data-dev
    environment:
      - ADV_HOST=172.21.171.70
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9092:9092"