version: '3.8'
services:
  service:
    image: ghcr.io/axitera/meetup-docker-2022/nice-2-meet-u-service:latest
    environment:
      - KAFKA_HOST=${MY_HOST_IP}
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    ports:
      - 28080:8080
      - 28000:8000
      - 29000:9000
    depends_on:
      - database
      - kafka
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetup
  kafka:
    image: lensesio/fast-data-dev
    environment:
      - ADV_HOST=${MY_HOST_IP}
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9092:9092"